spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQARpxSqS7gMc7wyWTnsfTBXyw0yzyHimBkEYJArWN0vlwAOSIcRAe0kNhqDaV4mrR1XG+IxOQ8Mvba4F6hGwHqTlxQqgnJm76SrCzZmdeHolZ+KPPctoJvICj+Vf/ZAXFyTcrQmgP/iZT/XObkp6gSm3FbpwN7YLMeElN9wW7TCMNfn6DzTVIaVhlR1U7/a+Sb+u4SGrJcTM/OCV5Ew51ByHjD6lGkz5lp+il41JO6z4Ko+cljhEM987uYXM3LkvX9yF90B3ZEl8uaQp8xvLrF7BH2qC8iD0nb0gao23agkCwsdUMIiSiQFL4DUeXYUaYwdwGvDPBcXPwzvsKmwM+2iNj20LZ+4f6a9b6tKeAWXzCwdZt+KKnDIEJ7N4TbW+m8='

token:
  expiration_time: 864000000
  secret: '{cipher}AQCDHEQgecHIrEI3MaGpyl3Gu5Np32/xHIAfdPrCMGXZNF1y8K1jSqg1A9Ed8+9Uuui3m7EUG59IFkhFM/mj6QYfMHQQmESEyq0Mk0r22cupOBd+X+ICJtAUlwXCD45ZKu9IXaFPoqeN0waMav5MHn+6myHNsYZLm4euTyETUWz8hCkMHijCdjkcrTXDqJSOzl3i/cxKpiwePUGr4G3GlUG54jq3YNSeZHeBx5sFVYkAA1g4h8gbNqj+ZvibbNCwYmSaCr1X85KxWJLwuOZs/EUam9LeizLRO2I0hEHuZoR//qFB5RmqYYCbLTa8ahTIv/kYTCmjNz1GeqM2QBqLiMwylD9UBCfxcpdD5uskSdV8Tl3Br7W9NXI/h2BGKYE3i+Uj9tplmCrZbtZrCYXmpC2h'

gateway:
  ip: 127.0.0.1

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: There is a no item!
